apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/csiber/hello-k3s
  newName: ghcr.io/csiber/hello-k3s
  newTag: 7707229ada04102fb943f82ff83238c1057f7006
