apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: demo
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "300m"
      memory: "256Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: soft-quota
  namespace: demo
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
