name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-publish-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-k3s:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/hello-k3s:latest

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomize image tag
        working-directory: k8s
        run: |
          kustomize edit set image ghcr.io/${{ github.repository_owner }}/hello-k3s=ghcr.io/${{ github.repository_owner }}/hello-k3s:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit & push manifest bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add k8s/kustomization.yaml
          git commit -m "ci: image -> ${{ github.sha }}" || echo "No changes to commit"
          git push
